const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Prepared from a starch-based batter that may contain eggs, milk and butter`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `A classic hamburger served with freshly made fries and dips.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `This is a great milkshake consisting of strawberries, banana, peaches, fruit juice and ice cream.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Made with eggs, bread, and herbs. One of the most popular foods. It is very much eaten as a breakfast or fast food, made with cheese.`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `A simple twist on a classic meat burger, substituting the meat patty with an egg.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `A creamy combination of ice cream,milk and oreo in a thick shake.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Juicy, meaty, greasily satisfying. The bun is slightly crunchy on the outside and soft inside. The cheese happily melting over the meat.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `A sandwich consisting of one cooked patty of ground meat, placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, smoked or flame broiled`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `A summer's delight made especilly for the ones in love to share a drink in the quarantine.`,
  },
];
export default menu;
